# Generated by Django 5.2.7 on 2025-11-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('production_ready', 'Production Ready'), ('approved', 'Approved'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
